name: Sync GitHub To Notion

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-github-to-notion:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Sync GitHub to Notion
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: |
          python scripts/sync_github_to_notion.py
